name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag app:latest
    - uses: actions/docker-container@v3
    - name: Creating Docker Conatiner
      run: docker run -td --name="app" -p 5000:5000 app:latest
